import { Layout } from 'components/projects/Layout/Layout';
import { Seo } from 'components/projects/Seo/Seo';
import useArticles, {
  fetchArticlePath,
  fetchArticles,
} from 'hooks/useArticles';
import type { NextPage } from 'next';
import { Article } from 'pages/api/article/list';
import { SWRConfig } from 'swr';

import styles from '../styles/Home.module.scss';

const Articles: React.FC<{
  articles: Article[];
  isLoading: boolean;
  isError: boolean;
}> = ({ articles, isLoading, isError }) => {
  if (isError) return <div>failed to load</div>;
  if (isLoading) return <div>loading...</div>;

  return (
    <>
      {articles.map(({ link, title, description }, index) => (
        <a href={link} className={styles.card} key={index}>
          <h2>{title} &rarr;</h2>
          <p>{description}</p>
        </a>
      ))}
    </>
  );
};

const Home: NextPage = () => {
  const { articles, isLoading, isError } = useArticles();

  return (
    <Layout>
      <Seo
        title="Create Next App"
        description="Generated by create next app"
        icon="/favicon.ico"
      />

      <main className={styles.main}>
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <Articles
            articles={articles}
            isLoading={isLoading}
            isError={isError}
          />
        </div>
      </main>
    </Layout>
  );
};

export async function getStaticProps() {
  // `getStaticProps` is executed on the server side.
  const articles = await fetchArticles(fetchArticlePath);
  return {
    props: {
      fallback: {
        fetchArticlePath: articles,
      },
    },
  };
}

export default function Page({ fallback }) {
  // SWR hooks inside the `SWRConfig` boundary will use those values.
  return (
    <SWRConfig value={{ fallback }}>
      <Home />
    </SWRConfig>
  );
}
