query fetchPromptTemplates($query: String) {
  promptTemplates(
    where: { _search: $query }
    first: 12
    orderBy: updatedAt_DESC
  ) {
    id
    title
    description
    base {
      content
      title
    }
    option {
      content
      title
    }
    updatedAt
  }
}

query fetchPromptTemplate($id: ID) {
  promptTemplate(where: { id: $id }) {
    id
    title
    description
    base {
      content
      title
    }
    option {
      content
      title
    }
    updatedAt
  }
}

mutation create($input: PromptTemplateCreateInput!) {
  createPromptTemplate(data: $input) {
    id
    title
    base {
      title
      content
    }
    option {
      title
      content
    }
  }
}

mutation publish($id: ID!) {
  publishPromptTemplate(where: { id: $id }, to: PUBLISHED) {
    id
  }
}
