fragment promptTemplate on PromptTemplate {
  id
  title
  description
  base {
    id
    title
    content
  }
  option {
    id
    title
    content
  }
  updatedAt
}

query fetchPromptTemplates($query: String) {
  promptTemplates(
    where: { _search: $query }
    first: 12
    orderBy: updatedAt_DESC
  ) {
    ...promptTemplate
  }
}

query fetchPromptTemplate($id: ID) {
  promptTemplate(where: { id: $id }) {
    ...promptTemplate
  }
}

mutation create($input: PromptTemplateCreateInput!) {
  createPromptTemplate(data: $input) {
    ...promptTemplate
  }
}

mutation update($id: ID, $input: PromptTemplateUpdateInput!) {
  updatePromptTemplate(data: $input, where: { id: $id }) {
    ...promptTemplate
  }
}

mutation publish($id: ID) {
  publishPromptTemplate(where: { id: $id }, to: PUBLISHED) {
    ...promptTemplate
  }
}
